### ISSUE TITLE
Cuda memory usage increase over time when training

### ISSUE THREAD

**Issue by xiwen1** [VDIGPKU/T-SEA#13]
Cuda memory usage increase over time when training. Is it a bug or feature? How can I fix it or avoid it. My training process will be killed when it comes to around 800 epoches due to cuda memory usage, but I need more.

**Comment by xiwen1** [comment]
We will definitely cite you if the bug can be fixed! it has stuck our work now.

**Comment by ziyannchen** [comment]
Hey, thx for reaching out. I'm sorry if this problem affected your progress.
This problem was posed in #4 by different users as well. We didn't run into this problem before. 
It may caused by a hardware difference. I'll try to train in a different server to reproduce it as soon as possible and will update the repo once it is fixed.

If there are any new ideas to help fix it, feel free to discuss them with us or create pull requests.

**Comment by ziyannchen** [comment]
Could you report your GPU info here?

**Comment by xiwen1** [comment]
#4 
The problem is solved referring to this.
